name: ngcgeoloc
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - affine=2.4.0
  - alsa-lib=1.2.3.2
  - appdirs=1.4.4
  - attrs=24.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - blosc=1.21.3
  - boost-cpp=1.74.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2025.11.12
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - curl=7.88.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - dataclasses=0.8
  - dbus=1.13.6
  - expat=2.4.8
  - ffmpeg=4.3
  - flit-core=3.8.0
  - fontconfig=2.14.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - freetype-py=2.3.0
  - freexl=1.0.6
  - future=0.18.3
  - gdal=3.1.4
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.13
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - harfbuzz=2.9.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.2
  - idna=3.4
  - imagecodecs-lite=2019.12.3
  - imageio=2.33.1
  - importlib_resources=5.12.0
  - intel-openmp=2021.4.0
  - jasper=1.900.1
  - joblib=1.1.1
  - jpeg=9e
  - json-c=0.15
  - jxrlib=1.1
  - kealib=1.4.14
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcurl=7.88.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdap4=3.20.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgdal=3.1.4
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.68.4
  - libglu=9.0.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libjpeg-turbo=2.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.0
  - libnghttp2=1.46.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libogg=1.3.4
  - libopencv=4.4.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=13.3
  - libprotobuf=4.25.3
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - llvm-openmp=12.0.1
  - locket=1.0.0
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - munkres=1.1.4
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.4
  - nettle=3.7.3
  - nspr=4.32
  - nss=3.69
  - numexpr=2.8.4
  - opencv=4.4.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=23.0
  - pandas=1.5.3
  - partd=1.2.0
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pooch=1.4.0
  - poppler=21.03.0
  - poppler-data=0.4.12
  - postgresql=13.3
  - proj=8.0.0
  - protobuf=4.25.3
  - pthread-stubs=0.4
  - py-opencv=4.4.0
  - pycparser=2.21
  - pyglet=1.5.27
  - pyopengl=3.1.6
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyrender=0.1.45
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywavelets=1.4.1
  - pyyaml=6.0
  - qt=5.12.9
  - rasterio=1.2.1
  - readline=8.2
  - requests=2.28.1
  - scikit-learn=1.3.0
  - scipy=1.10.0
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.9
  - snuggs=1.4.7
  - sqlite=3.41.1
  - tensorboardx=2.6.2.2
  - threadpoolctl=3.5.0
  - tiledb=2.2.9
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - tornado=6.1
  - trimesh=3.21.2
  - typing_extensions=4.12.2
  - tzcode=2022a
  - tzdata=2024b
  - urllib3=1.26.14
  - wheel=0.38.4
  - x264=1!157.20191217
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - yacs=0.1.8
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - albucore==0.0.17
      - albumentations==1.4.18
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - beautifulsoup4==4.13.3
      - cython==3.0.12
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - dsacstar==0.0.0
      - einops==0.8.1
      - esac==0.0.0
      - eval-type-backport==0.2.2
      - faiss-gpu==1.7.2
      - fast-pytorch-kmeans==0.2.2
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h5py==3.11.0
      - huggingface-hub==0.27.0
      - imgaug==0.4.0
      - importlib-metadata==8.5.0
      - jinja2==3.1.6
      - kornia==0.7.3
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - loguru==0.7.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - natsort==8.4.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - platformdirs==4.3.6
      - poselib==2.0.4
      - pretty==0.1
      - prettytable==3.11.0
      - propcache==0.2.0
      - psutil==7.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyproj==3.5.0
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - pytorch-lightning==2.4.0
      - pytorch-metric-learning==2.8.1
      - regex==2024.11.6
      - rich==14.0.0
      - safetensors==0.4.5
      - scikit-image==0.21.0
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - shapely==2.0.6
      - shtab==1.7.2
      - smmap==5.0.2
      - soupsieve==2.6
      - sympy==1.13.3
      - table==0.0.4
      - tifffile==2023.7.10
      - timm==1.0.15
      - tokenizers==0.15.2
      - torch==2.4.1
      - torchmetrics==1.5.2
      - tqdm==4.67.1
      - transformers==4.36.2
      - triton==3.0.0
      - turboreg-gpu==1.0
      - typeguard==4.4.0
      - typing-extensions==4.13.2
      - tyro==0.9.19
      - wandb==0.19.11
      - wcwidth==0.2.13
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/ubuntu/anaconda3/envs/ace
